services:
  api:
    env_file:
      - ./api/.env.prod

  queue-worker:
    env_file:
      - ./api/.env.prod

  scheduler:
    env_file:
      - ./api/.env.prod

  nginx:
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro

  client:
    build:
      args:
      - VITE_API_URL=https://verdko.com/api
    env_file:
      - ./client/.env.prod

  scraper:
    env_file:
      - ./scraper/.env.prod